# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ba8f716d9cf7162f23568f490ffd79ed2379bb5560890af07b00d05b3138c3800f065fa8e6f73be9b04d66f360d344384f1e35cacda06bfbe672f0260561ba

test:
  secret_key_base: 75613ce0e61df7d6929fe02710c08da9adead69bad98bf1f158927fc1f96eb32bea893079753bd7ceec992ec193aa49da2d28147e1a2815f99943a00814615e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
